
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.node1
    ports:
      - "8081:8080"

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.node2
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - node1
      - node2
