version: '3.8'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.node1
    ports:
      - "8081:8080"
    networks:
      node_network:
        ipv4_address: 192.168.5.16

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.node2
    ports:
      - "8082:8080"
    networks:
      node_network:
        ipv4_address: 192.168.5.91

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - node1
      - node2
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.5.0/24"
